-- Migration: create subscriptions table
-- Project: UPAEC / 7G Greens
-- Task: UPAEC-T-272-05
--
-- Records every active Square Subscription. A subscription is not tracked
-- until this row exists. The square_subscription_id is the canonical link
-- back to Square for webhook processing, cancellation, and status sync.
--
-- Run via: supabase db push  (or paste into Supabase SQL editor)
-- Depends on: 20260520_create_orders.sql (for the set_updated_at trigger)

create table if not exists public.subscriptions (
  -- Surrogate primary key (UUID, generated by Supabase)
  id                      uuid        primary key default gen_random_uuid(),

  -- Square references
  square_subscription_id  text        not null unique,
  square_customer_id      text        not null,
  square_card_id          text        not null,

  -- Plan details (denormalized for easy display / analytics without re-fetching Square)
  plan_variation_id       text        not null,
  plan_name               text        not null,
  cadence                 text        not null,    -- "WEEKLY" | "MONTHLY"

  -- Monetary amount in USD cents (always integer; avoids float precision issues)
  amount_cents            integer     not null check (amount_cents > 0),

  -- Subscriber contact
  customer_email          text        not null,
  customer_name           text        null,

  -- Subscription lifecycle status (mirrors Square: PENDING, ACTIVE, CANCELED, etc.)
  status                  text        not null default 'ACTIVE',

  -- Audit timestamps
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- Fast lookup by email (customer subscription history)
create index if not exists subscriptions_customer_email_idx
  on public.subscriptions (customer_email);

-- Fast lookup by Square customer ID (webhook processing, cancellation)
create index if not exists subscriptions_square_customer_id_idx
  on public.subscriptions (square_customer_id);

-- Fast lookup by Square subscription ID (webhook dedup, status sync)
create index if not exists subscriptions_square_subscription_id_idx
  on public.subscriptions (square_subscription_id);

-- Auto-update updated_at on row changes (reuses the function from orders migration)
drop trigger if exists subscriptions_set_updated_at on public.subscriptions;
create trigger subscriptions_set_updated_at
  before update on public.subscriptions
  for each row execute function public.set_updated_at();

-- RLS: enable row-level security (service role bypasses; anon/auth roles blocked by default)
alter table public.subscriptions enable row level security;

comment on table public.subscriptions is
  'Persists every Square Subscription created via the UPAEC subscribe flow. '
  'square_subscription_id links back to Square for webhook sync and cancellation.';
