-- Migration: create orders table
-- Project: UPAEC / 7G Greens
-- Task: UPAEC-T-272-07
--
-- Records every completed Square payment as a persistent order.
-- A charge is not a real order until this row exists.
--
-- Run via: supabase db push  (or paste into Supabase SQL editor)

create table if not exists public.orders (
  -- Surrogate primary key (UUID, generated by Supabase by default)
  id            uuid primary key default gen_random_uuid(),

  -- Square payment reference
  payment_id    text        not null unique,

  -- Item purchased
  item_id       text        not null,
  item_name     text        not null,

  -- Monetary amount (always in USD cents; avoids float precision issues)
  amount_cents  integer     not null check (amount_cents > 0),

  -- Buyer contact — nullable; captured when checkout form includes email
  customer_email text       null,

  -- Square-hosted receipt URL
  receipt_url   text        null,

  -- Payment status as returned by Square (e.g. 'COMPLETED')
  status        text        not null default 'COMPLETED',

  -- Audit timestamps (both set by DB; updated_at maintained by trigger below)
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Index for fast lookup by email (order history, re-send confirmation)
create index if not exists orders_customer_email_idx
  on public.orders (customer_email)
  where customer_email is not null;

-- Index for payment_id lookups (webhook dedup, refund flows)
create index if not exists orders_payment_id_idx
  on public.orders (payment_id);

-- Auto-update updated_at on row changes
create or replace function public.set_updated_at()
  returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- RLS: enable row-level security (service role bypasses; anon/auth roles blocked by default)
alter table public.orders enable row level security;

-- Service role can read/write all rows (used by server-side API routes).
-- Anon / authenticated users have no access by default — add policies here
-- when a customer order-history route ships (phase 272+).
comment on table public.orders is
  'Persists every completed Square payment. A charge is not a real order until this row exists.';
